// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Estuda.AI - Aprenda mais, em menos tempo",
  description: "Transforme qualquer texto em resumos, perguntas e flashcards com inteligência artificial. Cole seu conteúdo e estude com eficiência.",
  keywords: "estudos, IA, resumos, flashcards, questões, aprendizado, inteligência artificial",
  authors: [{ name: "Estuda.AI" }],
  openGraph: {
    title: "Estuda.AI - Aprenda mais, em menos tempo",
    description: "A IA que transforma textos em aprendizado. Cole seu conteúdo e receba resumos, flashcards e questões simuladas.",
    type: "website",
    locale: "pt_BR",
  },
  twitter: {
    card: "summary_large_image",
    title: "Estuda.AI - Aprenda mais, em menos tempo",
    description: "Transforme qualquer texto em resumos, perguntas e flashcards com IA.",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
        <Script
          async
          src="https://www.googletagmanager.com/gtag/js?id=GA_MEASUREMENT_ID"
        />
        <Script id="google-analytics">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'GA_MEASUREMENT_ID');
          `}
        </Script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} font-inter antialiased bg-white text-gray-900`}
      >
        {children}
      </body>
    </html>
  );
}